### ISSUE TITLE
Include CourtListener's id for each case

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/courtlistener-export#7]
Let's include cluster.id as an "id" field for each case. This will let people connect opinions between different versions of the export, and construct URLs to the CourtListener frontend.

**Comment by jordanparker6** [comment]
For example:

`www.courtlistener.com/opinion/{opinion_id}/{slug}/`

The opinions array would need to include the `opinon_id` to achieve this. The `slug` is already included.
